### ISSUE TITLE
Fehler beim Speichern von Sätzen in SQLite

### ISSUE THREAD

**Issue by davidak** [davidak/satzgenerator.de#2]
Ich vermute, dass es Probleme gibt, weil SQLite kein DateTime kennt.

```
Fehler: Satz konnte nicht in die Datenbank gespeichert werden.
Fehler: Satz konnte nicht in die Datenbank gespeichert werden.
Fehler: Satz konnte nicht in die Datenbank gespeichert werden.
Fehler: Satz konnte nicht in die Datenbank gespeichert werden.
Fehler: Satz konnte nicht in die Datenbank gespeichert werden.
Fehler: Satz konnte nicht in die Datenbank gespeichert werden.
Fehler: Satz konnte nicht in die Datenbank gespeichert werden.
Fehler: Satz konnte nicht in die Datenbank gespeichert werden.
Fehler: Satz konnte nicht in die Datenbank gespeichert werden.
Fehler: Satz konnte nicht in die Datenbank gespeichert werden.
Der Satz konnte auch beim 10. Versuch nicht in die Datenbank gespeichert werden. Das ist vermutlich ein Datenbank-Problem und es sollte der Administrator informiert werden.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/Library/Python/2.7/site-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "satzgenerator.py", line 185, in generator
    redirect('/' + neuen_satz_generieren())
  File "satzgenerator.py", line 91, in neuen_satz_generieren
    if debug: print('Satz in Datenbank gespeichert mit uid ' + uid)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by davidak** [comment]
http://docs.sqlalchemy.org/en/latest/dialects/sqlite.html#sqlite-data-types
